# Generated by Django 4.2.4 on 2024-08-12 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('max_price', models.IntegerField(verbose_name='حداکثر قیمت')),
            ],
            options={
                'verbose_name': 'فیلتر قیمت',
                'verbose_name_plural': 'فیلتر های قیمت',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان در url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/categories', verbose_name='تصویر دسته بندی')),
                ('icon_name', models.CharField(max_length=20, verbose_name='نام آیکون')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_parent', models.BooleanField(verbose_name='والد است')),
                ('caption', models.CharField(db_index=True, max_length=300, verbose_name='عنوان')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_categories', to='product_module.productcategory', verbose_name='دسته بندی ها')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_tag', to='product_module.producttag', verbose_name='تگ والد')),
            ],
            options={
                'verbose_name': 'تگ محصول',
                'verbose_name_plural': 'تگ های محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='نام برند')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان در url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/categories', verbose_name='تصویر دسته بندی')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
                ('category', models.ManyToManyField(related_name='brands_categories', to='product_module.productcategory', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='نام محصول')),
                ('features', models.TextField(blank=True, null=True, verbose_name='ویژگی ها محصول')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.productbrand', verbose_name='برند')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='product_module.productcategory', verbose_name='دسته بندی ها')),
                ('tags', models.ManyToManyField(related_name='products_tag', to='product_module.producttag', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
