# Generated by Django 4.2.4 on 2024-08-12 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_producttag_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_categories', to='product_module.productcategory', verbose_name='دسته بندی ها'),
        ),
    ]
