# Generated by Django 4.2.4 on 2024-08-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_alter_producttag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='iamge',
            field=models.ImageField(blank=True, null=True, upload_to='images/products', verbose_name='عکس محصول'),
        ),
    ]
