# Generated by Django 4.2.4 on 2024-08-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_product_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='iamge',
            new_name='image',
        ),
    ]
