# Generated by Django 4.2.4 on 2024-08-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_rename_iamge_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='مقدار فروخته شده'),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='میزان بازدید'),
        ),
    ]
