# Generated by Django 4.2.4 on 2024-08-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_product_sales_count_product_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttag',
            name='short_description',
            field=models.CharField(db_index=True, max_length=360, null=True, verbose_name='توضیحات کوتاه'),
        ),
    ]
