# Generated by Django 4.2.4 on 2024-08-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_remove_producttag_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
