# Generated by Django 4.2.4 on 2024-08-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0010_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.TextField(blank=True, null=True, verbose_name='سایزهای محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.TextField(blank=True, null=True, verbose_name='رنگ های محصول'),
        ),
    ]
