# Generated by Django 4.2.4 on 2024-08-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0011_product_sizes_alter_product_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='توضیحات اصلی'),
        ),
    ]
