# Generated by Django 4.2.4 on 2024-08-15 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0013_alter_product_description_productquestionsanswers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productquestionsanswers',
            options={'verbose_name': 'پرسش و پاسخ محصول', 'verbose_name_plural': 'پرسش ها و پاسخ های مقاله'},
        ),
        migrations.RenameField(
            model_name='productquestionsanswers',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='productquestionsanswers',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='product_module.productquestionsanswers', verbose_name='والد'),
        ),
        migrations.AlterField(
            model_name='productquestionsanswers',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productquestionsanswers',
            name='text',
            field=models.TextField(verbose_name='متن پرسش و پاسخ'),
        ),
    ]
