# Generated by Django 4.2.4 on 2024-08-16 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_module', '0014_alter_productquestionsanswers_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('comment', models.TextField(verbose_name='کامنت')),
                ('rate', models.PositiveIntegerField(verbose_name='امتیاز')),
                ('likes', models.PositiveIntegerField(blank=True, null=True, verbose_name='لایک')),
                ('di_likes', models.PositiveIntegerField(verbose_name='دیس لایک')),
                ('pros', models.TextField(blank=True, null=True, verbose_name='نقات مثبت')),
                ('cons', models.TextField(blank=True, null=True, verbose_name='نقات منفی')),
                ('buyer', models.BooleanField(default=False, verbose_name='خریدار ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرسش و پاسخ محصول',
                'verbose_name_plural': 'پرسش ها و پاسخ های مقاله',
            },
        ),
    ]
