# Generated by Django 4.2.4 on 2024-08-16 11:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_module', '0015_productcomments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductComments',
            new_name='ProductComment',
        ),
        migrations.AlterModelOptions(
            name='productcomment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
    ]
