# Generated by Django 4.2.4 on 2024-08-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0016_rename_productcomments_productcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='di_likes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='دیس لایک'),
        ),
    ]
