# Generated by Django 4.2.4 on 2024-08-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0018_alter_productcomment_cons_alter_productcomment_pros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomment',
            old_name='di_likes',
            new_name='dis_likes',
        ),
    ]
