# Generated by Django 4.2.4 on 2024-08-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0021_remove_productcomment_dis_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomment',
            old_name='dis_likes',
            new_name='dislikes',
        ),
    ]
