# Generated by Django 4.2.4 on 2024-08-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0022_rename_dis_likes_productcomment_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='satisfaction_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
