# Generated by Django 4.2.4 on 2024-08-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0023_product_satisfaction_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='satisfaction_percentage',
        ),
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.FloatField(default=0.0, verbose_name='میانگین نمرات محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='satisfaction',
            field=models.FloatField(default=0.0, verbose_name='درصد رضایت مشتری از محصول'),
        ),
    ]
