# Generated by Django 4.2.4 on 2024-08-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0024_remove_product_satisfaction_percentage_product_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sales_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='view_count',
        ),
        migrations.AddField(
            model_name='pricefilter',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='فعال / غیرفعال'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttag',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='فعال / غیرفعال'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='فعال / غیرفعال'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(db_index=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='is_active',
            field=models.BooleanField(db_index=True, verbose_name='فعال / غیرفعال'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(db_index=True, verbose_name='فعال / غیرفعال'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='rate',
            field=models.PositiveIntegerField(db_index=True, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='productquestionsanswers',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت'),
        ),
    ]
