# Generated by Django 4.2.4 on 2024-08-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0025_remove_product_sales_count_remove_product_view_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales_count',
            field=models.IntegerField(db_index=True, default=0, editable=False, verbose_name='مقدار فروخته شده'),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.IntegerField(db_index=True, default=0, editable=False, verbose_name='میزان بازدید'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=300, verbose_name='نام محصول'),
        ),
    ]
