# Generated by Django 4.2.4 on 2024-08-23 19:49

from django.db import migrations
import utils.custom_fileds


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0027_product_discount_expiry_product_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=utils.custom_fileds.WebPImageField(blank=True, null=True, upload_to='images/products', verbose_name='عکس محصول'),
        ),
    ]
