# Generated by Django 4.2.4 on 2024-08-23 21:42

from django.db import migrations
import utils.custom_fileds


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0028_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrand',
            name='image',
            field=utils.custom_fileds.WebPImageField(blank=True, null=True, upload_to='images/categories', verbose_name='تصویر دسته بندی'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=utils.custom_fileds.WebPImageField(blank=True, null=True, upload_to='images/categories', verbose_name='تصویر دسته بندی'),
        ),
    ]
