# Generated by Django 4.2.4 on 2024-08-26 15:03

from django.db import migrations
import webp_imagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0029_alter_productbrand_image_alter_productcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=webp_imagefield.fields.WebPImageField(blank=True, null=True, upload_to='images/products', verbose_name='عکس محصول'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='image',
            field=webp_imagefield.fields.WebPImageField(blank=True, null=True, upload_to='images/categories', verbose_name='تصویر دسته بندی'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=webp_imagefield.fields.WebPImageField(blank=True, null=True, upload_to='images/categories', verbose_name='تصویر دسته بندی'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=webp_imagefield.fields.WebPImageField(upload_to='images/product-gallery', verbose_name='تصویر'),
        ),
    ]
