# Generated by Django 4.2.4 on 2024-08-20 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_module', '0027_product_discount_expiry_product_discount_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='کد تخفیف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مقدار تخفیف')),
                ('valid_from', models.DateTimeField(verbose_name='تاریخ اعتبار از')),
                ('valid_to', models.DateTimeField(verbose_name='تاریخ اعتبار تا')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='کد پیگیری سفارش')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ثبت سفارش')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='تحویل گیرنده')),
                ('recipient_phone', models.CharField(max_length=15, verbose_name='شماره موبایل')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('final_price', models.IntegerField(verbose_name='مبلغ کل')),
                ('delivery_date', models.DateField(verbose_name='تاریخ تحویل')),
                ('delivery_time_range', models.CharField(max_length=50, verbose_name='زمان تحویل')),
                ('delivery_price', models.IntegerField(verbose_name='هزینه ارسال')),
                ('is_paid', models.BooleanField(verbose_name='نهایی شده / نشده')),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_module.discountcode', verbose_name='کد تخفیف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='تعداد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='order_module.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
    ]
