# Generated by Django 4.2.4 on 2024-08-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(default=True, max_length=20, verbose_name='رنگ محصول'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='هزینه ارسال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time_range',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='زمان تحویل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='مبلغ نهایی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='نهایی شده / نشده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='کد پیگیری سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تحویل گیرنده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره موبایل'),
        ),
    ]
