# Generated by Django 4.2.4 on 2024-08-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0002_orderitem_color_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رنگ محصول'),
        ),
    ]
