# Generated by Django 4.2.4 on 2024-08-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0027_product_discount_expiry_product_discount_percent'),
        ('account_module', '0003_user_favorite_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_products',
            field=models.ManyToManyField(related_name='favorite_products', to='product_module.product', verbose_name='محصولات ذخیره شده'),
        ),
    ]
