# Generated by Django 4.2.4 on 2024-08-23 21:42

from django.db import migrations
import utils.custom_fileds


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_alter_user_favorite_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=utils.custom_fileds.WebPImageField(blank=True, null=True, upload_to='images/profile', verbose_name='تصویر کاربر'),
        ),
    ]
