# Generated by Django 4.2.4 on 2024-08-26 15:03

from django.db import migrations
import webp_imagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=webp_imagefield.fields.WebPImageField(blank=True, null=True, upload_to='images/profile', verbose_name='تصویر کاربر'),
        ),
    ]
